# Generated by Django 4.1 on 2025-01-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.driver'),
        ),
    ]
