# Generated by Django 4.1 on 2025-01-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_task_driver'),
    ]

    operations = [
    ]
