# Generated by Django 4.1 on 2025-01-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20250126_1338'),
    ]

    operations = [
    ]
